[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "lxml>=6.0.0",
    "pdfplumber>=0.11.7",
    "requests>=2.32.4",
    "scrapy>=2.13.3",
]
